### ISSUE TITLE
Interior House - Polish Floor

### ISSUE THREAD

**Issue by Rankazze** [bronchouse/remodel#9]
Guest Bathroom
Remove Toilet
Polish floor
Install Toilet

**Comment by ExperimentsInHonesty** [comment]
Wrote to Brian

>  Hi Brian,
> 
> Robby told me that you replied to his text and that you are in Arizona on a job.  If you are not able to come do the final high speed buffing with the natural gloss finish between now and 7th, are you able to recommend someone else?  Also are there any steps that we should do once we take up the paper?  Do we need to wet mop or anything first to get up any dust before the buffing is done?
> 
> The move out date on my apartment downtown is Midnight on Feb 8th.  I am not able to extend my lease (I did try).
> 
> Please let me know by the end of day tuesday 1/18 so I can plan accordingly.
> 
> Thanks,

https://mail.google.com/mail/u/1/#search/brian%40aciflooring.com/CllgCJNxNSMpDTGpGcXsSxNcTNDBQrVmZGgzlMBnpdRblgBlCfVCzhCMFhZdJfSGQSCdgVPnRxq

**Comment by ExperimentsInHonesty** [comment]
Wrote to this guy:
https://www.yelp.com/biz/concrete-reviver-lake-elsinore-2?osq=floor+polishing
He is coming Wednesday 20th  at 4pm

**Comment by ExperimentsInHonesty** [comment]
email to Brian - https://mail.google.com/mail/u/1/#sent/DmwnWrRpdLgLlHRHqVQphvKLHTmBwGthSnqVDSfNxxtvvdcfRxkSFdprBcdbdxshLpfdwdrRzZBb

**Comment by ExperimentsInHonesty** [comment]
Floor polished on 2/24/2021 and silicone sealer was added
